#!/bin/bash
# -------------------------------------------------------------------------
# ediff: wrapper for emacs ediff
#
# Copyright 2016 by Yonghyun Hwang <freeaion@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# Some rights reserved.
# -------------------------------------------------------------------------

EDIFF_GCONST_VERSION="1.0"

# print usage
function ediff_prt_cmd_heading
{
    echo "======================"
    echo "ediff ${EDIFF_GCONST_VERSION}: wrapper for emacs ediff"
    echo ""
}

function ediff_prt_usage
{
    ediff_prt_cmd_heading
    echo 1>&2 Usage: ediff "[FILE_1] [FILE_2] [FILE_3]"
    echo " + key bindings while diffing:"
    echo "       \"n\"            : jump to next diff"
    echo "       \"p\"            : jump to previous diff"
    echo "       \"?\"            : get online help for diffing"
    echo "       \"ctrl-x ctrl-o\": switch between source & diff frames"
    echo "       \"ctrl-x ctrl-c\": exit"
    echo ""
    echo " + examples:"
    echo "    1) diff two files (2-way diff)"
    echo "       > ediff file1 file2"
    echo ""
    echo "    2) diff three files (3-way diff)"
    echo "       > ediff file1 file2 file3"
    echo ""
}

function ediff_chk_precond
{
    if ! which emacs >& /dev/null; then
        echo "cannot find emacs. stop here."
        return 1
    fi

    if [ $# -lt 2 ] || [ $# -gt 3 ]; then
        ediff_prt_usage
        return 1
    fi

    for file in "$@"; do
        if [ ! -f ${file} ]; then
            printf "${0##*/}[error]: \"${file}\" is not file. all params should be existing files\n"
            return 1
        fi
    done

    return 0
}

##############################################
# Main script starts from here!

if ! ediff_chk_precond "$@"; then
    exit 1
fi

quoted1=${1//\\/\\\\}; quoted1=${quoted1//\"/\\\"}
quoted2=${2//\\/\\\\}; quoted2=${quoted2//\"/\\\"}

if [ -z ${3:-} ]; then
    emacs -Q -nw --eval "(ediff \"$quoted1\" \"$quoted2\")"
else
    quoted3=${3//\\/\\\\}; quoted3=${quoted3//\"/\\\"}
    emacs -Q -nw --eval "(ediff-files3 \"$quoted1\" \"$quoted2\" \"$quoted3\")"
fi

exit $?
